language: scala
scala:
   - 2.11.7
jdk:
  - oraclejdk8
install:
  - gem install sass
env:
  - DIR=core TASKS=test,scripted
  - DIR=site TASKS=compile
script:
  - cd $DIR
  - echo ${TASKS/,/ } | xargs sbt
