language: scala

scala:
   - 2.11.7

jdk:
  - oraclejdk8

addons:
  hosts:
    - localhost

before_script:
  - gem update --system
  - gem install selenium-webdriver
  - gem install sass

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
