language: scala
scala:
   - 2.11.7
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
install:
  - gem install sass
env:
  - DIR=core TASKS=test,scripted
  - DIR=site TASKS=compile
script:
  - cd $DIR
  - echo ${TASKS/,/ } | xargs sbt
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
